// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwqTbn9xSuVh3d2u42SUAqSSHvHZ3SatE',
    appId: '1:511488541089:web:c8d0c4f749ef69fc50cbe0',
    messagingSenderId: '511488541089',
    projectId: 'guess-who-13c57',
    authDomain: 'guess-who-13c57.firebaseapp.com',
    storageBucket: 'guess-who-13c57.firebasestorage.app',
    measurementId: 'G-8H34NE9VJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3LkOMXLKxw9NTVBkCeNcdRxGdDQRBc6s',
    appId: '1:511488541089:android:1eab8d2aa76c2d2050cbe0',
    messagingSenderId: '511488541089',
    projectId: 'guess-who-13c57',
    storageBucket: 'guess-who-13c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjxdwfsJOf8gPjlxsXpw4GAXYYS-DvDBw',
    appId: '1:511488541089:ios:9331af8838698b9350cbe0',
    messagingSenderId: '511488541089',
    projectId: 'guess-who-13c57',
    storageBucket: 'guess-who-13c57.firebasestorage.app',
    iosBundleId: 'com.guesswho.3d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjxdwfsJOf8gPjlxsXpw4GAXYYS-DvDBw',
    appId: '1:511488541089:ios:9331af8838698b9350cbe0',
    messagingSenderId: '511488541089',
    projectId: 'guess-who-13c57',
    storageBucket: 'guess-who-13c57.firebasestorage.app',
    iosBundleId: 'com.guesswho.3d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwqTbn9xSuVh3d2u42SUAqSSHvHZ3SatE',
    appId: '1:511488541089:web:4e9fb2ac1652cb4a50cbe0',
    messagingSenderId: '511488541089',
    projectId: 'guess-who-13c57',
    authDomain: 'guess-who-13c57.firebaseapp.com',
    storageBucket: 'guess-who-13c57.firebasestorage.app',
    measurementId: 'G-4DDQ83QB7F',
  );
}
